import Head from "next/head";
import Link from "next/link";
import { Toaster, toast } from "sonner";
import styles from "./index.module.css";
import { Dashboard } from "@/components/dashboard";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import "react-tabs/style/react-tabs.css";
import { BigCalendar } from "../components/calendar/big-calendar";

export default function Home() {
	return (
		<>
			<Head>
				<title>Dream Lodge</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					<Toaster />
					<Tabs>
						<h1 className={styles.title}>
							Dream <span className={styles.pinkSpan}>Lodge</span>
						</h1>
						<TabList>
							<Tab>Home</Tab>
							<Tab>Dashboard</Tab>
							<Tab>Calendar</Tab>
						</TabList>

						<TabPanel>
							<h2 className={styles.title}>
								<span className={styles.pinkSpan}>Home</span>
							</h2>
							<div className={styles.cardRow}>
								<Link
									className={styles.card}
									href="https://create.t3.gg/en/usage/first-steps"
									target="_blank"
								>
									<h3 className={styles.cardTitle}>First Steps →</h3>
									<div className={styles.cardText}>
										Just the basics - Everything you need to know to set up your
										database and authentication.
									</div>
								</Link>
								<Link
									className={styles.card}
									href="https://create.t3.gg/en/introduction"
									target="_blank"
								>
									<h3 className={styles.cardTitle}>Documentation →</h3>
									<div className={styles.cardText}>
										Learn more about Create T3 App, the libraries it uses, and
										how to deploy it.
									</div>
								</Link>
							</div>
						</TabPanel>

						<TabPanel>
							<h2 className={styles.title}>
								<span className={styles.pinkSpan}>Dashboard</span>
							</h2>
							<button type="button" onClick={() => toast("My first toast")}>
								Give me a toast
							</button>
							<Dashboard />
						</TabPanel>

						<TabPanel>
							<h2 className={styles.title}>
								<span className={styles.pinkSpan}>Calendar</span>
							</h2>
							<BigCalendar />
						</TabPanel>
					</Tabs>
				</div>
			</main>
		</>
	);
}
